{% set name = "jsonLookup" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95bb1cd51e04e21c1b5a70ec5faa597b8435cb94da868fbbd5d1550fc7c88432

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - django

test:
  requires:
    - python {{ python_min }}
  imports:
    - jsonLookup

about:
  home: https://pypi.org/project/jsonLookup/
  summary: jsonLookup, searching in MySQL JSON field in Django.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
